<?php

namespace Tests\Unit;

use App\Services\CriadorDeSerie;
use App\Services\RemovedorDeSerie;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RemovedorDeSerieTest extends TestCase
{
    use RefreshDatabase;

    /** @var Serie */
    private $serie;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $criadorDeSerie = new CriadorDeSerie();
        $nomeSerie = 'Nome de teste';
        $this->serie = $criadorDeSerie->criarSerie($nomeSerie, 1, 1);
    }

    public function testRemoverUmaSerie()
    {
        $this->assertDatabaseHas(
            'series',
            ['id' => $this->serie->id]
        );
        $removeDeSerie = new RemovedorDeSerie();
        $nomeSerie = $removeDeSerie->removerSerie($this->serie->id);
        $this->assertIsString($nomeSerie);
        $this->assertEquals('Nome de teste', $nomeSerie);
        $this->assertDatabaseMissing(
            'series',
            ['id', $this->serie->id]
        );
    }
}
